{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Used ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_usage_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage by LNN",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_cpu_usage_lnn{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Free",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_writeable_bytes{cluster_name=~\"$Cluster\"} - cluster_usage_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Net Throughput by LNN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "cluster_net_troughput_lnn{cluster_name=~\"$Cluster\"} * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cluster_cpu_usage{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Used Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_usage_bytes{cluster_name=~\"$Cluster\"} / cluster_total_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dedupe Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_dedupe_ratio{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster SyncIQ Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "cluster_siq_troughput{cluster_name=~\"$Cluster\"} * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_usage_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_writeable_bytes{cluster_name=~\"$Cluster\"} - cluster_usage_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Net Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "cluster_net_troughput{cluster_name=~\"$Cluster\"} * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cluster_total_bytes{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster IFS Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "cluster_ifs_troughput{cluster_name=~\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}